### PR TITLE
Add sidebar links

### PR DESCRIPTION
**Pull request by ZucchiniZe**
Added sidebar links, would you like me to put the layout in each markdown file?

### CODE REVIEW

**Comment by jbranchaud** [comment]
@ZucchiniZe Can you check that all the links work? I noticed for instance that you used `tipsandtricks.html` when that file is actually called `TipsAndTricks.md`. Thanks!

**Comment by ZucchiniZe** [comment]
Yeah I have been running a local jekyll instance using -w to test, yes they do work.

**Comment by jbranchaud** [comment]
:+1:, thanks for checking!

**Comment by jbranchaud** [comment]
Ooh, so it also works for me locally, but on the server, not so much. I am pushing a fix now.

**Comment by jbranchaud** [comment]
Fixed in #62.

**Comment by ZucchiniZe** [comment]
Thanks.

**Pull request merged**
